karakeep-app/karakeep

README.md, apps/workers/crawlerWorker.ts, apps/workers/inference.ts, apps/workers/openaiWorker.ts, apps/workers/package.json, apps/workers/searchWorker.ts, docs/docs/01-intro.md, docs/docs/02-installation.md, docs/docs/03-configuration.md, packages/db/drizzle.config.ts, packages/db/package.json, packages/shared/config.ts, pnpm-lock.yaml, tooling/eslint/base.js
=> Feature: Add support for local models using ollama

apps/browser-extension/manifest.json
added csp rule to allow firefox to connect to http endpoints
=> Firefox Plugin - NetworkError on Sign in #23

apps/workers/openaiWorker.ts
added a trim to tags to prevent whitespaces at the beginning/end of tags
=> AI infered tags can contain " " at the beginning #184

apps/web/components/dashboard/bookmarks/EditorCard.tsx
showing the error message created on the server side, to have a bit more information #179
=> more detailed error message in case the bookmark is already part of the list #179

apps/cli/src/commands/bookmarks.ts, apps/cli/src/commands/lists.ts, apps/cli/src/commands/tags.ts, apps/cli/src/commands/whoami.ts, apps/cli/src/index.ts, apps/cli/src/lib/globals.ts, apps/cli/src/lib/output.ts
added a way to get proper json output
=> bookmark list output is not a valid JSON #150

docs/docs/02-Installation/03-archlinux.md
=> add Arch Linux installation

apps/web/components/dashboard/bookmarks/EditorCard.tsx
Fixes: Text paste not working due to the image paste feature introduced in #228
=> fix: text paste bug introduced with image paste

.gitignore, apps/web/components/dashboard/preview/BookmarkPreview.tsx, apps/workers/crawlerWorker.ts, packages/db/drizzle/0023_late_night_nurse.sql, packages/db/drizzle/meta/0023_snapshot.json, packages/db/drizzle/meta/_journal.json, packages/db/schema.ts, packages/shared/assetdb.ts, packages/shared/types/bookmarks.ts, packages/trpc/routers/bookmarks.ts
Added a new sourceUrl column to the asset bookmarks
Added transforming a link bookmark pointing at a pdf to an asset bookmark
made sure the "View Original" link is also shown for asset bookmarks that have a sourceURL
updated gitignore for IDEA
=> feature request: pdf support #28

packages/queue/db.ts, packages/queue/drizzle.config.ts, packages/queue/drizzle/0000_wonderful_talisman.sql, packages/queue/drizzle/meta/0000_snapshot.json, packages/queue/drizzle/meta/_journal.json, packages/queue/index.ts, packages/queue/options.ts, packages/queue/package.json, packages/queue/queue.ts, packages/queue/runner.test.ts, packages/queue/runner.ts, packages/queue/schema.ts, packages/queue/tsconfig.json, packages/queue/types.ts, packages/queue/vitest.config.ts, pnpm-lock.yaml
chore: Add a new sqlite based queue package
=> chore: Add a new sqlite based queue package

apps/web/components/dashboard/bookmarks/BookmarkedTextViewer.tsx, apps/web/components/ui/markdown-component.tsx, apps/web/package.json, pnpm-lock.yaml
added the possibility to add checkboxes
=> [Feature Request] inside an item, add the Memos "checkbox" feature todo a check list into an item #300

kubernetes/chrome-service.yaml, kubernetes/kustomization.yaml
=> Adding chrome-service.yaml and adapt kustomization.yaml

apps/web/components/dashboard/lists/CollapsibleBookmarkLists.tsx
=> [Feature Request] Alphabetical sorting for lists #315

apps/web/components/dashboard/bookmarks/TagsEditor.tsx
readded the scrollbar again, so it is obvious that the list is scrollable
=> Improve tagging behavior #368

apps/web/server/auth.ts
using email address as fallback, if the name is not available
=> OAuth login failed: No profile #410

apps/web/components/dashboard/BulkBookmarksAction.tsx
=> [Feature Request] Multiple bookmark selection copy to clipboard #427

apps/cli/src/commands/lists.ts
Added a command that returns the ids of the bookmarks in a list
=> [CLI] Ability to get all bookmark IDs of a list #442

apps/web/components/ui/markdown-component.tsx, apps/web/package.json, pnpm-lock.yaml
added remarkBreaks plugin to properly handle single newlines
=> Single linebreaks are lost when viewing textnote card #549

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/feature_request.yml
I found that making issues was a little inconsistent, so I wanted to throw my two cents in and provide some issue templates! I've taken inspiration from both NewPipe and BookStack's issue templates and modified them to fit Hoarder.
=> Adding issue templates

apps/web/components/dashboard/admin/AddUserDialog.tsx, apps/web/components/dashboard/admin/ChangeRoleDialog.tsx, apps/web/components/dashboard/admin/ResetPasswordDialog.tsx, apps/web/components/dashboard/admin/UserList.tsx, apps/workers/inference.ts, packages/shared/types/admin.ts, packages/shared/types/users.ts, packages/trpc/routers/admin.ts, packages/trpc/routers/users.ts
added the possibility to create a user as admin, to solve #495 
added the possibility to reset the password as an admin to solve #544
added the possibility to change the role as an admin to solve #560
We should probably also add some documentation on how to reset the admin password, if you managed to even forget that one.
=> User management

docker/docker-compose.dev.yml, docker/docker-compose.yml, docs/docs/07-Development/01-setup.md, kubernetes/meilisearch-deployment.yaml
=> upgrade meilisearch to v1.11.1

packages/shared/inference.ts
=> docs: update inference.ts

apps/web/lib/i18n/locales/zhtw/translation.json, packages/shared/langs.ts
=> Add zh-TW Traditional Chinese locale

docs/docs/02-Installation/01-docker.md
I changed some language in the docker installation documentation that I found confusing when I tried to follow the steps. I am one of vagabonds fleeing Omnivore as it is shutting down. I am not very familiar with docker, but I was able to get it to work. I believe these minor clarifications would improve the documentation.
=> Docker Installation Minor Language Update

apps/web/lib/i18n/locales/tr/translation.json, packages/shared/langs.ts
- Added Turkish translations for the application's interface in apps/web/lib/i18n/locales/tr/translation.json.
- Updated packages/shared/langs.ts to include Turkish ("tr") in the language mappings.
- No deletions were made, and the changes ensure full localization support for Turkish-speaking users.
=> Added Turkish translation.

apps/web/components/settings/ImportExport.tsx, apps/web/lib/i18n/locales/en/translation.json, apps/web/lib/importBookmarkParser.ts
Imports Linkwarden expoprted bookmarks from multiple Linkwarden collections. Import includes bookmarks, tags, and original creation time.
=> feat: add Linkwarden importer

apps/web/lib/i18n/locales/hr/translation.json, packages/shared/langs.ts
=> i18n: Added Croatian translation

.github/workflows/ci.yml, apps/web/package.json, package.json, packages/db/drizzle.ts, packages/shared/package.json, packages/trpc/package.json, packages/trpc/testUtils.ts, turbo.json
Reverts hoarder-app/hoarder#807
=> Revert "ci: Run tests on push"

docs/docs/02-Installation/01-docker.md, docs/docs/02-Installation/04-kubernetes.md, docs/versioned_docs/version-v0.15.0/02-Installation/01-docker.md, docs/versioned_docs/version-v0.16.0/02-Installation/01-docker.md, docs/versioned_docs/version-v0.16.0/02-Installation/04-kubernetes.md, docs/versioned_docs/version-v0.17.0/02-Installation/01-docker.md, docs/versioned_docs/version-v0.17.0/02-Installation/04-kubernetes.md, docs/versioned_docs/version-v0.18.0/02-Installation/01-docker.md, docs/versioned_docs/version-v0.18.0/02-Installation/04-kubernetes.md, docs/versioned_docs/version-v0.19.0/02-Installation/01-docker.md, docs/versioned_docs/version-v0.19.0/02-Installation/04-kubernetes.md, docs/versioned_docs/version-v0.20.0/02-Installation/01-docker.md, docs/versioned_docs/version-v0.20.0/02-Installation/04-kubernetes.md, docs/versioned_docs/version-v0.21.0/02-Installation/01-docker.md, docs/versioned_docs/version-v0.21.0/02-Installation/04-kubernetes.md
Simple change: `hightly` -> `highly`.
=> Typo fix in docs

apps/workers/feedWorker.ts
=> chore: set firefox user-agent for rss reader

CONTRIBUTING.md
=> [RFC] Add CONTRIBUTING.md

docs/docs/02-Installation/03-archlinux.md
docs: update Arch Linux installation
=> docs: update Arch Linux installation

apps/landing/src/Homepage.tsx
Fix #1222 
Now the year updates automatically.
=> Landing: Made the year in footer dynamic.

apps/web/components/dashboard/lists/EditListModal.tsx, apps/web/components/dashboard/lists/ListHeader.tsx, apps/web/lib/i18n/locales/en/translation.json, packages/db/drizzle/0043_puzzling_blonde_phantom.sql, packages/db/drizzle/meta/0043_snapshot.json, packages/db/drizzle/meta/_journal.json, packages/db/schema.ts, packages/open-api/hoarder-openapi-spec.json, packages/shared/types/lists.ts, packages/trpc/models/lists.ts
Fix: #1017 
Now we can add short description(100 chars max) to lists.
Also, i am attaching pictures showing how the description in UI looks. Please inform me, if you need any changes to the ui.
=> feat(web): Optionally add short description to lists

CONTRIBUTING.md, docs/docs/11-FAQ.md
Hi, small PR to replace hoarder with karakeep in the contributing file and FAQ.
=> chore: replace hoarder with karakeep in CONTRIBUTING.md and FAQ

apps/landing/src/Homepage.tsx
Fix #1291 
Now all hrefs open in new tab.
=> landing: all external links open in new tab

docs/docs/07-Development/01-setup.md
- **doc: clarify dev instruction**
- **doc: fix outdated meilisearch version mentionned + mention embeddings**
very minimal changes
=> docfix: minor: dev setup instructions

docs/docs/09-command-line.md, docs/docs/13-community-projects.md
- **doc: mention karakeep-python-api in the community projects**
- **doc: also mention karakeep-python-api in the cli section**
=> doc: mention karakeep-python-api in community projects

packages/open-api/karakeep-openapi-spec.json, packages/open-api/lib/lists.ts, packages/trpc/models/lists.ts
=> fix(api): make PUT bookmark to a list idempotent

docs/docs/12-troubleshooting.md
This is to fix #1333 as I ran into this issue myself.
=> doc: document how to upgrade meilisearch / migrate meilisearch db

apps/web/components/dashboard/tags/TagPill.tsx
Fixes the issue with drag-n-drop not working on Firefox based browsers
=> Fixes #1016

docs/docs/07-Development/01-setup.md, docs/docs/07-Development/03-database.md
Noticed a few command were wrong also removed a bunch of +'s that caused horizontal scrolling (but then again who doesn't love pluses!)
=> doc: Update database docs

docs/docs/02-Installation/01-docker.md
- **doc: typo**
- **doc: mention meilisearch upgrade**
Fix #543 in [that comment](https://github.com/karakeep-app/karakeep/issues/543#issuecomment-2909504350)
=> doc: mention meilisearch in the updating section

karakeep-linux.sh
I noticed that using the log for StdOut and StdError would stop working under certain circumstances. Using 'append' instead of 'file' allows the file to be read while opened.
=> karakeep-linux.sh fix: use 'append' instead of 'file' for logs

docs/docs/03-configuration.md, packages/api/utils/assets.ts, packages/api/utils/upload.ts, packages/e2e_tests/docker-compose.yml, packages/e2e_tests/package.json, packages/e2e_tests/setup/startContainers.ts, packages/e2e_tests/tests/assetdb/assetdb-utils.ts, packages/e2e_tests/tests/assetdb/interface-compliance.test.ts, packages/e2e_tests/tests/assetdb/local-filesystem-store.test.ts, packages/e2e_tests/tests/assetdb/s3-store.test.ts, packages/shared/assetdb.ts, packages/shared/config.ts, packages/shared/package.json, pnpm-lock.yaml
=> feat: Add support for S3 as an asset storage layer

apps/web/app/api/bookmarks/export/route.tsx
Quick fix resolving https://github.com/karakeep-app/karakeep/issues/1793
=> Renamed export filename to karakeep

apps/web/lib/i18n/locales/fr/translation.json
=> Update french translation.json

docs/docs/14-guides/02-search-query-language.md
=> doc: clarify that groups can't be negated

docs/docs/09-command-line.md
=> Docs: Update 09-command-line.md

apps/web/components/settings/ImportExport.tsx
Add a loading indicator to the export button #1787 
---
- Use `button` instead of `Link` for starting the export  
- Use **Fetch API** to create a function that starts the download process  
- Wrap this function with `useQuery` to track the loading state  
- Disable the export button and show a spinner while fetching the export data  
- Create a download link dynamically and start the download
- show a toast if an error occurred
https://github.com/user-attachments/assets/53c14212-36d9-4361-802a-5deaa97d20db
=> feat: Show loading indicator while export file is being generated #1787

apps/web/components/dashboard/bookmarks/NoBookmarksBanner.tsx
=> fix: fix public list sharing for empty lists
