docker/docker-compose.dev.yml
docker/docker-compose.yml

Necessary context: https://github.com/MohamedBassem/hoarder-app/issues/42
Changes the chrome container version in docker-compose from 100 to 102, because version 102 has a `linux/arm64` artifact and it can thus run on ARM architecture.

Bump chrome container version to 102 to enable linux/arm64 support on it

---

.env.sample
docs/docs/07-Development/01-setup.md

updated the documentation on how to set up the development environment

Development Instructions are incomplete/not working #145

---

apps/web/components/dashboard/bookmarks/AssetCard.tsx

Hi there! Very simple tweak to make my and my spouse's lives a bit easier--as designers, we make heavy use of the ability to save images in Hoarder!
By default, link bookmarks have a clickable preview image and title, and the maximize button in the action bar opens a modal with the local text-only archive. Uploaded images don't have an external link, so clicking the preview image or title does nothing, and only clicking the maximize button opens the details modal so the full image can be viewed.
This change just makes preview images for image assets open the details modal--the same behavior as the maximize button. Makes them a little easier to hit on mobile 😸
It's my first time working with NextJS, so I hope everything looks okay. Thanks for making Hoarder; we're really enjoying it so …

feature: Clicking preview for image assets brings up the details modal

---

apps/web/components/dashboard/preview/AssetContentSection.tsx

My husband gave me the idea for this PR 😉 As part of his illustration work, he saves a lot of images for drawing reference, and it's helpful to be able to open them in a split view on his iPad so he can have his reference right next to the canvas. Unfortunately, the pinch-to-zoom gesture doesn't work on images when Hoarder is added to the Home Screen as a web app. This tweak just links the image in the preview modal to the original file, so clicking it will open it in a new tab that can be zoomed, panned, etc.
(Side note: I originally had a much more complicated implementation for this, with a toggle for fullscreen mode and a pinch-pan-zoom library for manipulating the image when fullscreened. But, as it turns out, Apple hasn't made the Fullscreen API available for browsers other than …

feature(web): Clicking an image in the preview modal will open it in a new tab

---

apps/web/components/dashboard/tags/AllTagsView.tsx
apps/web/components/dashboard/tags/TagPill.tsx
apps/web/components/ui/toggle.tsx
apps/web/lib/drag-and-drop.ts
apps/web/package.json
pnpm-lock.yaml

Added drag&drop functionality
Allowing sorting the tags by name, as this is more intuitive
Just a crude change to get some feedback. As I am no UI dev, I am thankful for any improvement ideas.

Improve merging of tags by simple drag and drop #144

---

apps/web/components/dashboard/bookmarks/TagsEditor.tsx
apps/web/components/dashboard/preview/BookmarkPreview.tsx

Another fresh batch of styles from me today! 🧑‍🍳
- Set the tag input field to 100% width to fix an issue where the tag select dropdown could overflow when inputting short sections of text.
- Fixed an issue where the corners of the tag input field and select dropdown did not match the corners of the note field. (Below image shows the issue at 400% zoom.)
- Changed some styles to align labels to their respective fields and make field contents more visually consistent (text size, colors, etc).

ui(web): Various tweaks for input fields in preview modal

---

apps/web/components/dashboard/bookmarks/EditorCard.tsx
apps/web/components/ui/multiple-choice-dialog.tsx

Added a reusable dialog
opening a dialog that allows you to decide if you want to import multiple URLs at once if you provide only that

Allow adding multiple URLs at once #158

---

apps/cli/src/commands/bookmarks.ts

realized that the cli is not using cursorV2 and is causing an infite loop/going out of memory if bookmarks created at the same second exist

Switched to cursorV2 to make use of the fix for #140

---

apps/browser-extension/manifest.json
apps/browser-extension/src/background/background.ts
apps/browser-extension/src/utils/settings.ts
apps/browser-extension/tsconfig.json

Adds a context menu entry when a hoarder instance is configured and removes it again, if it is not configured anymore

Feature request: Browser extension "Open your Hoarder saves" #188

---

apps/web/components/dashboard/UploadDropzone.tsx
apps/web/components/dashboard/bookmarks/EditorCard.tsx

I've added an onPaste event to the Textfield to allow pasting images, instead of just dragging and dropping them. This is to help those who often take screenshots without saving them.

feature: support pasting image in the textfield

---

packages/trpc/routers/bookmarks.ts

I so no use of having a limit in the update only while the create have no such limit.

fix: Remove the bookmark update text limit

---

apps/web/components/dashboard/bookmarks/EditorCard.tsx

This PR contains 2 fixes: 
1- Allow resizing the textfield in the list layout only, it does not break the UI and it gives a better experince when writing notes because the area for writing in the list mode is so small
2- Auto resizing the textfield to fit the content to a max of half the screen height

feature: Enhance the bookmark textarea in the list layout

---

apps/landing/app/page.tsx

- Images on landing page are getting stretched on safari

[UI] Landing page Image breaking on safari

---

apps/web/app/dashboard/archive/page.tsx
apps/web/app/dashboard/bookmarks/page.tsx
apps/web/app/dashboard/favourites/page.tsx
apps/web/app/dashboard/search/page.tsx
apps/web/components/dashboard/ChangeLayout.tsx
apps/web/components/dashboard/bookmarks/Bookmarks.tsx
apps/web/components/dashboard/bookmarks/TopNav.tsx
apps/web/components/dashboard/lists/ListHeader.tsx
apps/web/components/dashboard/sidebar/SidebarProfileOptions.tsx

- Move layout control on top of bookmarks grid. 
- Currently, it’s hidden in the settings menu at the bottom left, and people sometimes don’t notice it
https://github.com/hoarder-app/hoarder/assets/45597394/9fa6a7da-d55a-4caa-b87e-b4543e6affaa

Move layout control to main screen

---

apps/web/app/dashboard/settings/page.tsx
apps/web/components/dashboard/settings/ApiKeySettings.tsx
apps/web/components/dashboard/settings/ChangePassword.tsx
apps/web/components/dashboard/settings/DeleteApiKey.tsx
apps/web/components/dashboard/settings/UserDetails.tsx
apps/web/components/dashboard/sidebar/Sidebar.tsx

- Show basic details like email and name in user settings
- UI changes for the user settings page
- Refactored code for sidebar component

[UI] Changes for user settings page

---

apps/workers/crawlerWorker.ts
packages/db/index.ts
packages/shared/assetdb.ts
packages/trpc/routers/bookmarks.ts

Extracted out functions to silently delete assets and to update them after crawling
Generalized the mapping of assets to bookmark fields to make extending them easier

refactoring asset types

---

apps/browser-extension/src/SavePage.tsx
apps/cli/src/commands/bookmarks.ts
apps/mobile/app/dashboard/add-link.tsx
apps/mobile/app/dashboard/add-note.tsx
apps/mobile/app/sharing.tsx
apps/mobile/components/bookmarks/BookmarkCard.tsx
apps/mobile/components/bookmarks/UpdatingBookmarkList.tsx
apps/mobile/lib/upload.ts
apps/web/components/dashboard/UploadDropzone.tsx
apps/web/components/dashboard/bookmarks/BookmarkCard.tsx
apps/web/components/dashboard/bookmarks/BookmarkOptions.tsx
apps/web/components/dashboard/bookmarks/BookmarkedTextEditor.tsx
apps/web/components/dashboard/bookmarks/EditorCard.tsx
apps/web/components/dashboard/preview/AssetContentSection.tsx
apps/web/components/dashboard/preview/BookmarkPreview.tsx
apps/web/components/dashboard/preview/EditableTitle.tsx
apps/web/components/dashboard/preview/LinkContentSection.tsx
apps/web/components/dashboard/preview/TextContentSection.tsx
apps/workers/crawlerWorker.ts
packages/db/drizzle/0025_aspiring_skaar.sql
packages/db/drizzle/meta/0025_snapshot.json
packages/db/drizzle/meta/_journal.json
packages/db/schema.ts
packages/shared-react/utils/bookmarkUtils.ts
packages/shared/assetdb.ts
packages/shared/types/bookmarks.ts
packages/trpc/routers/bookmarks.test.ts
packages/trpc/routers/bookmarks.ts

Introduced an enum to have better type safety
cleaned up the code and based some code on the type directly

Added the bookmark type to the database

---

apps/web/components/dashboard/bookmarks/EditorCard.tsx

fixed an issue that would half the size of the textarea in grid/masonry layout after submitting a bookmark
additionally it would resize the bookmark input field after each input on the textarea

fixed the editorcard textarea

---

apps/web/app/layout.tsx

Thank you for creating such awesome software.
This PR addresses the issue of Inter fonts not loading for CJK (Chinese, Japanese, and Korean) character sets, resulting in an inconsistent appearance. To improve consistency of appearance, a sans-serif fallback is specified. This ensures that if the Inter font fails to load, the generic sans-serif font will be used to maintain a consistent look across different character sets.
Original:
This PR:
Input text: "日本語表示確認用サンプル文"

fix(web): Add sans-serif fallback for Inter font in CJK character sets

---

apps/cli/src/lib/trpc.ts
apps/web/lib/providers.tsx
packages/shared-react/providers/trpc-provider.tsx

limiting the length of the URL for batched requests to prevent 431 errors

last version bookmarks import error #281

---

apps/workers/crawlerWorker.ts

passing in the URL of the page to have the proper URL for resolving relative paths

monolith is not embedding SVG files correctly #289

---

apps/mobile/app/signin.tsx

Hi, small pull request to fix the removal of the slash at the end of a server address on mobile.
It was mentioned in https://github.com/hoarder-app/hoarder/issues/311 and I used the same code as in the linked code by @MohamedBassem.
Extension:
https://github.com/hoarder-app/hoarder/blob/809a9bc35ad4b975dbd4eacc5c6aa8ab285b6d9a/apps/browser-extension/src/NotConfiguredPage.tsx#L25

fix: trim slash from url for the mobile app

---

apps/web/components/dashboard/bookmarks/LinkCard.tsx

added "noreferrer" to the links to prevent sending referrers to bookmarked pages
I have added it to the links on the cards itself for now as that is not a change in behavior. 
We could do it for the details also, but it needs some discussion

Removing referrer header when clicking on links #387

---

apps/web/components/signin/CredentialsForm.tsx

The current behavior to disable only the button when `DISABLE_SIGNUPS=true` is really easy to misunderstood https://github.com/hoarder-app/hoarder/issues/52

Clear disabled signups message

---

apps/web/app/api/health/route.ts

Hopefully i did all right. 
Checked functionality locally.
was quite hard to find out how to disable the hooks (ESlint checking failed)

add healthecheck api endpoint

---

packages/trpc/routers/bookmarks.test.ts
packages/trpc/routers/bookmarks.ts

fixed an issue that caused all existing tags to be assigned to a new bookmark

[Bug Report] Importing bookmarks adds all tags to all bookmarks #421

---

apps/workers/crawlerWorker.ts
apps/workers/openaiWorker.ts
apps/workers/searchWorker.ts

extended logging when an exception occurrs, so it is possible to see the stacktrace of a failed execution

inference job failed #424

---

apps/web/components/dashboard/sidebar/AllLists.tsx
apps/web/components/dashboard/sidebar/SidebarItem.tsx

This PR enhances the accessibility and user experience of the SidebarItem component by expanding the clickable area to cover the entire item.

fix(web): Improve SidebarItem tap target accessibility

---

apps/web/components/dashboard/BulkBookmarksAction.tsx
apps/web/components/dashboard/bookmarks/BookmarkOptions.tsx
apps/workers/crawlerWorker.ts
packages/shared/queues.ts
packages/trpc/routers/bookmarks.ts

Added the ability to start a full page crawl for links and also in bulk operations
added the ability to refresh links as a bulk operation as well
I have split the PR into 2 parts for now. This one is the easy part and will just allow triggering the full page archive. The next one will deal with the changes required to allow multiple archives to be stored, as we discussed in discord.

[Feature Request] Ability to select what to "crawl full page archive" #398

---

docs/docs/02-Installation/01-docker.md

"greated" should be "greeted".

Fix typo in Docker Installation docs

---

docker/.env.sample
docker/Dockerfile.dev
docker/docker-compose.dev.yml

I had issues running the Docker development environment without first setting up a local development environment.
And put the Environment variables into a seperate .env file

Fixing Docker Dev Environment

---

docker/Dockerfile

To get changelogs shown with Renovate a docker container has to add the source label described in the OCI Image Format Specification.
For reference: https://github.com/renovatebot/renovate/blob/main/lib/modules/datasource/docker/readme.md

Add Source Label to Dockerfile

---

docker/Dockerfile

i added the healthcheck to the AIO and legacy web container. 
checked on my AIO instance:
```
{
"Status":"healthy",
"FailingStreak":0,
"Log":[
{
"Start":"2024-10-07T21:23:19.83382568+02:00",
"End":"2024-10-07T21:23:20.003640388+02:00",
"ExitCode":0,
"Output":"Connecting to 127.0.0.1:3000 (127.0.0.1:3000)\nremote file exists\n"
}
]
}
```

Add HEALTHCHECK to Dockerfile

---

apps/web/app/dashboard/archive/page.tsx
apps/web/app/dashboard/bookmarks/page.tsx
apps/web/app/dashboard/favourites/page.tsx
apps/web/app/dashboard/layout.tsx
apps/web/app/dashboard/search/page.tsx
apps/web/components/dashboard/GlobalActions.tsx
apps/web/components/dashboard/header/Header.tsx
apps/web/components/dashboard/header/ProfileOptions.tsx
apps/web/components/dashboard/lists/ListHeader.tsx
apps/web/components/dashboard/sidebar/AllLists.tsx
apps/web/components/dashboard/sidebar/ModileSidebar.tsx
apps/web/components/dashboard/sidebar/Sidebar.tsx

Add a global header to the layout with the following updates:
- Relocate the Search and Bulk Actions from individual pages to the header.
- Move Settings, Admin and general Settings to the header.
Issues this PR addresses
- #520 
https://github.com/user-attachments/assets/461dee82-358b-4b6a-818c-9ea04ab43d0d
https://github.com/user-attachments/assets/3cf331d1-524e-467b-9026-433391a8a23f

Add header in layout

---

apps/browser-extension/src/SignInPage.tsx
apps/web/components/signin/CredentialsForm.tsx
apps/web/lib/clientConfig.tsx
docs/docs/03-configuration.md
packages/shared/config.ts
packages/trpc/auth.ts
packages/trpc/routers/apiKeys.ts
packages/trpc/routers/users.ts

changed the flag to also disallow logging in via password
The extensions will also no longer be allowed to log in via username/password then

[Feature Request] Allow to disable default password log in after SSO is configured #406

---

apps/web/components/dashboard/tags/AllTagsView.tsx
apps/web/components/dashboard/tags/DeleteTagConfirmationDialog.tsx
apps/web/components/dashboard/tags/TagPill.tsx

improved performance by not handling hover in css
also rendering the draggable div only if draggable mode is active

long delay when selecting tags in UI #382

---

apps/web/components/dashboard/bookmarks/EditorCard.tsx
apps/web/components/dashboard/search/SearchInput.tsx

added ctrl+k to focus the search bar
added escape to delete the input of the search bar
fixed behavior of ctrl+e on windows, which would otherwise focus the chrome searchbar

[Feature Request] Keyboard Shortcut & Search Improvements #449

---

docs/docs/02-Installation/06-debuntu.md
hoarder-linux.sh

Hi @MohamedBassem  - thank you so much for your help with getting the Proxmox LXC script going. Hopefully it's ready to be merged soon!
This PR adds an all-in-one bash installer/updater script that is very similar to the ones in their repo. It adds most of the suggestions that you had for that one, such as separating the data and config dirs from the install dir, but also adds support for Ubuntu 24.04 as well as Debian 12. I have tested it extensively on both platforms.
I've also written the documentation for the script because I figured why not?
Please let me know what you think and if this would be a good addition to installation methods for Hoarder.

Add Linux install script and documentation

---

apps/browser-extension/src/components/ListsSelector.tsx
apps/browser-extension/src/components/TagsSelector.tsx

increased size to have the same size as the input field that triggers it
Looks like this afterwards:

nested Lists do not fit well in browser extension window #535

---

docs/docs/02-Installation/06-debuntu.md
docs/versioned_docs/version-v0.20.0/02-Installation/06-debuntu.md

Unfortunately I missed this mistake back when it was added.

Fix broken link in Debian/Ubuntu install doc

---

docs/docs/12-community-projects.md
docs/versioned_docs/version-v0.20.0/12-community-projects.md

Following the publication of the API, I recently created a [Telegram Bot](https://github.com/Madh93/hoarderbot) that allows users to save bookmarks to Hoarder directly through Telegram.
I've had the habit of adding my bookmarks in Telegram for years, and with this bot, I can continue using that workflow while also benefiting from the automatic tags generated by Hoarder :smile:

docs: Add Telegram Bot to community projects

---

apps/landing/app/page.tsx

Tweak the landing page to use "GitHub" instead of "Github" in header nav, hero buttons, and footer nav

fix(landing): update GitHub capitalization

---

apps/web/components/dashboard/bookmarks/BookmarkLayoutAdaptingCard.tsx

I imported a bunch of old saves from Pocket and found it hard to tell how old the saves were when browsing
I added the year to the Bookmark Card footer date format string when the bookmark is created over a year ago. It doesn't take up too much space, hope nobody minds the few characters
Happy to move code around or take another stab at this. Thanks!
<details>
<summary>screenshots showing grid and compact bookmark cards</summary>
</details>

feat: show createdAt year in card footer when created over a year ago

---

apps/cli/src/commands/bookmarks.ts

**Summary:**
This merge request introduces a title option to the bookmark add CLI command, allowing users to specify a title for a link(s) at the time of bookmark creation.
**Details:**
Previously, users had to update a bookmark after creation to set a title, which added an unnecessary step. By including a `--title` option in the bookmark add command, this enhancement streamlines the workflow and improves user experience.

feat: Add title option for adding bookmarks from the CLI

---

docs/docs/06-openai.md
docs/versioned_docs/version-v0.20.0/06-openai.md

This link currently redirects to the ChatGPT subscription-based pricing page, I've updated it with the URL for the model pricing page.

Fix openAI pricing link

---

apps/mobile/app/dashboard/(tabs)/lists.tsx
apps/mobile/lib/utils.ts

It's a small thing, but it was bugging me a lot 😬
| Before: | After: |
|:---:|:---:|
| <img src="https://github.com/user-attachments/assets/b90eb594-b88b-4520-9fc4-2ee96c0e74e4" width="300px" /> | <img src="https://github.com/user-attachments/assets/3bcfe048-8a7f-4e71-9375-f6c49bbd227b" width="300px" /> |
| <img src="https://github.com/user-attachments/assets/9591fb69-9399-45d0-b511-17841f249c47" width="300px" /> | <img src="https://github.com/user-attachments/assets/211ac054-4e76-4b83-925e-bf66dd9eb7bc" width="300px" /> |

fix: margin for "Lists" tab content

---

apps/browser-extension/src/NotConfiguredPage.tsx
apps/mobile/app/signin.tsx

Added URL protocol validation for mobile app and browser extension.

feat: add URL protocol validation

---

hoarder-linux.sh

Script will now exit on errors (and provide some info) and when there is an unset variable. Added check for Corepack v0.31.0 in update function.

Hoarder Debian/Ubuntu install script - Add error handling; other small fixes

---

apps/mobile/app/dashboard/_layout.tsx

The color for the navigation back button and navigation title in dark mode is not adapted and therefore cannot be differentiated from the dark background. Below, I'm sharing some before after screenshots to make the issue more easier to grasp.
This PR attempts at fixing the bug: https://github.com/hoarder-app/hoarder/issues/829

fix: add header class name corresponding to dark mode for text color

---

docs/docs/07-Development/01-setup.md

Hoarder uses node version 22, and makes use of `corepack` features. Instructions for setting those up correctly were missing.

docs: Add instructions for node environment setup

---

apps/workers/assetPreprocessingWorker.ts

I haven't tested if the typos broke anything, but might as well fix now before v0.23.0.
Was introduced by [bbed0ad](https://github.com/hoarder-app/hoarder/commit/bbed0adac4267b2deb14a5b50a4a9844f6e5cafe)

fix(workers): Small typo fix in assetPreprocessingWorker.ts

---

apps/web/app/api/v1/bookmarks/[bookmarkId]/summarize/route.ts
packages/open-api/hoarder-openapi-spec.json
packages/open-api/lib/bookmarks.ts

I added this in two commits. One is just for me. I had a few issues getting this running locally on a Linux box. It could just be a me problem :|
The second commit has the addition of a subroute for the summary mutation. It should return the bookmark object with the summarized contents. Please feel free to add or remove any commits and I'll do my best to address any feedback.
Thanks for a fantastic project.
Addresses: https://github.com/hoarder-app/hoarder/issues/523

Adds summarize action to the public API (proxy to TRPC mutation)

---

apps/web/server/auth.ts
docs/docs/03-configuration.md
packages/shared/config.ts

Small change to add a new env variables for OAuth timeouts, on some configurations, particularly on lower-end hardware (Such as my homelab orange pi), the authentication provider can take too much time to respond, with results in a timeout and failed authentication
The same behavior has been reported over at Homarr, which uses next-auth as well: https://github.com/ajnart/homarr/issues/1995
(My homelab is an orangepi zero3, the auth provider is Authentik)

feat(auth): Added env variable for OAuth timeout

---

docs/docs/11-FAQ.md

Thanks for the great app and helpful FAQ entry! I'm by no means a database user but needed to change the password and didn't get it to work initially. Figured it our pretty quickly by myself but might be helpful to other people, too. I took the liberty to slightly adjust the formatting as well so that the command fits in one line but feel free to change as you like. Thanks!

docs: Fixed missing semicolon in update admin password section

---

apps/web/components/dashboard/preview/BookmarkPreview.tsx

Fix #1114 
Added target="_blank" attribute to the Link tag.
Now on clicking view original in bookmark details opens in a new tab.

ui(web): Clicking view original now opens in a blank tab

---

packages/shared/langs.ts

As I see in the codebase, Hoarder has already been translated to Ukrainian: https://github.com/hoarder-app/hoarder/blob/main/apps/web/lib/i18n/locales/uk/translation.json
But it's not possible to select Ukrainian language from the UI.

Enable Ukrainian language

---

apps/web/components/shared/sidebar/Sidebar.tsx

Hoarder displays information about it's version in the sidebar. This PR adds an improvement that turns this text into a link to Github release page.
https://github.com/user-attachments/assets/9249978d-b667-43b0-9bf6-8821b24880c7

Link to Github release page in web sidebar

---

packages/shared/langs.ts

- Added `"ko": "Korean"` to `langNameMappings` in `langs.ts`.
- Korean translation file already exists in `locales/ko/translation.json`.
This allows users to select Korean in the language dropdown from the settings page.

i18n: Add Korean language

---

docker/docker-compose.dev.yml
docker/docker-compose.yml
packages/e2e_tests/docker-compose.yml

Hi, as mentioned on discord this PR updates meilisearch to 1.13.3.
The big difference comes with 1.12.0 (https://www.meilisearch.com/blog/meilisearch-1-12) as it's introducing a new indexing engine which improves speed and should reduce memory usage. This works fine locally as reported by [others](https://discord.com/channels/1223681308962721802/1223681309503651844/1328993475496120341).
I directly moved to the current latest version 1.13.3 as it seems there are no breaking changes related to the codebase: https://github.com/meilisearch/meilisearch/releases/tag/v1.13.0 or [docker hub ](https://hub.docker.com/layers/getmeili/meilisearch/v1.13.3/images/sha256-c4d6ab59c18d7b3636e82af862c31861ccf8afb3e9c14dddf9d3e868840667cd). 1.13.0 also introduces AI-powered search which could maybe be handy …

Update meilisearch version to 13.3 in both docker compose files

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/feature_request.yml
.github/ISSUE_TEMPLATE/question.yml

While creating an issue yesterday I noticed that it still contains the old name. 
I replaced hoarder with karakeep in all three github templates.

Replace hoarder with karakeep in github issue templates

---

apps/web/components/dashboard/lists/EditListModal.tsx

Currently when adjusting the emoji for a list, the Popover-Content box is smaller than the actual emoji picker "box" as seen on the screenshot:
I fixed this problem with `PopoverContent className="w-auto">` which was also used in https://github.com/karakeep-app/karakeep/blob/cf97bace33fdd14f29ce947d55d17cba8fa85c11/apps/web/components/dashboard/bookmarks/EditBookmarkDialog.tsx#L283
With this fix it looks like this:

fix: fit popover content box to emoji picker size

---

apps/mobile/app.json

This adds the "monochromeImage" setting to add support for [Themed App Icons](https://developer.android.com/develop/ui/views/launch/icon_design_adaptive).
I tested it locally on an android emulator, and it looks like this:
Closes #885

feat(mobile/android): Add monochrome app icon

---

apps/web/components/dashboard/bookmarks/BookmarkOptions.tsx

Fix #846 
Now the copy link button is greyed out(disabled) when clipboard is unavailable.

ui(web): Copy link button greyed out when clipboard not available

---

docs/docs/02-Installation/06-debuntu.md
docs/docs/14-Guides/04-hoarder-to-karakeep-migration.md
docs/versioned_docs/version-v0.23.1/02-Installation/06-debuntu.md
docs/versioned_docs/version-v0.23.1/14-Guides/04-hoarder-to-karakeep-migration.md
karakeep-linux.sh

- Adds a migrate function so users can convert their Hoarder install to a Karakeep install
- The function will also check for an update after finishing the migration
- Various fixes and optimisations
- Update docs with migration info
- Replace mentions of Hoarder with Karakeep in Debuntu install page

hoarder-linux.sh > karakeep-linux.sh v2.1

---

apps/workers/crawlerWorker.ts

Fix https://github.com/hoarder-app/hoarder/discussions/869
Close the browser instance after crawling if browserConnectOnDemand is enabled.
This should help users that are using service like browserless to reduce API usage.

Close browser if connect on demand

---

apps/web/components/dashboard/lists/ListOptions.tsx
apps/web/components/dashboard/lists/MergeListModal.tsx
apps/web/lib/i18n/locales/en/translation.json
apps/web/lib/i18n/locales/zh/translation.json
packages/shared-react/hooks/lists.ts
packages/shared/types/lists.ts
packages/trpc/models/lists.ts
packages/trpc/routers/lists.ts

This PR implements the feature requested in #1060, enabling users to merge contents from one list into another selected non-smart list with deduplication functionality.
- Added new merge functionality with deduplication between lists in trpc/models
- Added corresponding UI components to support the merge feature (see screenshot below)
<div style="display: flex; flex-direction: column; gap: 10px;">
</div>
New form labels have been added with translations for:
- English (en)
- Chinese (zh)
Translations for other supported languages are currently missing. I’m unsure if it’s expected for contributors to provide full translations, or if there’s a separate process for translations. I'm happy to add AI-generated translations if that's acceptable--just let me know.
During implementation, I …

feat(web): Add support for merging lists

---

apps/web/components/settings/ImportExport.tsx
apps/web/lib/i18n/locales/en/translation.json
apps/web/lib/i18n/locales/es/translation.json
apps/web/lib/importBookmarkParser.ts

Tab Session Manager is a browser extension ([Chrome](https://chromewebstore.google.com/detail/tab-session-manager/iaiomicjabeggjcfkbimgmglanimpnae), [Firefox](https://addons.mozilla.org/en-US/firefox/addon/tab-session-manager/)) to manually or automatically save the state of your browser (windows and tabs). I personally use it regularly to combat my hundreds of open tabs nature.
Adding support to import an Sessions export file.
The JSON file generated by Tab Session Manager contains multiple Sessions (all of the manually or automatically created), so the import will get the newest session and import all of the tabs across windows.

feat: Add import support for Tab Session Manager

---

apps/web/components/shared/sidebar/Sidebar.tsx

A. v${serverConfig.serverVersion} for docker images is translated to `vnightly` which is absent.
B. Link points to hoarder, which redirects after, probably legacy.
C. For me, it is more convenient to go directly to repository home and navigate from there.

FIxed sidebar link to github

---

apps/web/lib/i18n/locales/en_US/translation.json
packages/shared/langs.ts

This pull request focuses on improving language consistency in user-facing text and adding support for a new language variant. The changes include updates to English (US) translations for better grammar and tone, and the addition of `en_US` to the language mappings.
* Updated several strings in `apps/web/lib/i18n/locales/en_US/translation.json` to use consistent capitalization and tone, such as changing "Import as Text Bookmark" to "Import as text bookmark" and "No rules created yet, dude" to "No rules have been created yet" [[1]](diffhunk://#diff-1a4cddfab06d3ca6379b7f7fde5caeff84782ab02de2d6f8523fe827c82bb223L152-R155) [[2]](diffhunk://#diff-1a4cddfab06d3ca6379b7f7fde5caeff84782ab02de2d6f8523fe827c82bb223L269-R269) [[3]](diffhunk://#diff-1a4cddfab06d3ca6379b7f7fde5caeff84782ab02de2d6f852 …

Feature: Add US English as option in User Settings

---

apps/web/app/api/bookmarks/export/route.tsx
apps/web/components/settings/ImportExport.tsx
apps/web/lib/exportBookmarks.ts

This Pull Request supports exporting bookmarks in NETSCAPE-Bookmark-file-1 format.This feature will allow users to import bookmarks stored in Karakeep into most browsers.
1. Added a new `toNetscapeFormat` function in `exportBookmarks.ts` to convert bookmarks to NETSCAPE format
2. Updated the export endpoint to support format selection via query parameter
3. Enhanced the UI to allow users to choose between JSON and NETSCAPE formats
- Manually tested export in both formats
- Verified the exported NETSCAPE format can be imported back into Karakeep
- Confirmed the exported file can be imported into major browsers (Chrome, Firefox)
- Ensured special characters in URLs, titles, and tags are properly encoded

feat: Add NETSCAPE-Bookmark-file-1 export format support

---

docs/docs/09-mcp.md

Small typo fix. The JSON for the MCP was invalid.

Fix JSON in MCP documentation

---

karakeep-linux.sh

- Adds build command for the new MCP server feature 🚀
- Uses the recommended nightly of yt-dlp and will check for updates 📼
- Checks for system updates prior to karakeep install/update to avoid any surprises 😯
So I have to admit I am not at all on the MCP train, and I'm a little confused whether we need to build the server, or if it gets built and run when an MCP client initiates communication with karakeep. If it's the latter, then let me know and I'll get rid of the build commands for MCP 🙂

build(Debian): add mcp build; use nightly yt-dlp build; update system

---

apps/web/app/dashboard/search/page.tsx
apps/web/components/dashboard/SortOrderToggle.tsx
apps/web/components/dashboard/bookmarks/UpdatableBookmarksGrid.tsx
apps/web/lib/hooks/bookmark-search.ts
apps/web/lib/i18n/locales/en/translation.json
apps/web/lib/store/useSortOrderStore.ts
packages/shared/types/bookmarks.ts
packages/trpc/routers/bookmarks.ts

* add new sort order `relevance`
* retain existing(legacy) search's sort logic as `relevance`
* add new `asc` and `desc` sort logic
fixes #1335
I'm wasn't super sure how karakeep handles the translation, so let me know if there are follow up tasks, and anything else that I should tweak for this PR, thanks!

fix(search): add new relevance sort order

---

apps/web/components/dashboard/preview/BookmarkHtmlHighlighter.tsx

Hi, 
this PR adds the highlight functionality to touch devices, mostly mobile devices for the web version.
The main fix as discussed in the issue #1220  is using `onPointerUp={handlePointerUp} `instead of `onMouseUp`. 
With that change, the highlight menu appears on e.g. mobile. 
Besides that, I also adjusted `setMenuPosition` to move the menu below the selected text according to the `isMobile` check as in most cases the device context menu is above. The mobile check was found here and seems to be good for this use case:
https://stackoverflow.com/a/52855084/9950786
Here's how it now looks on mobile:
This doesn't adjust the web version:
**Current latest stable after selecting Qualcomm:**
**My PR:**

feat: position highlight menu based on device type

---

.prettierignore
apps/web/app/api/v1/bookmarks/[bookmarkId]/route.ts
apps/web/app/api/v1/bookmarks/route.ts
apps/web/app/api/v1/bookmarks/search/route.ts
apps/web/app/api/v1/lists/[listId]/bookmarks/route.ts
apps/web/app/api/v1/tags/[tagId]/bookmarks/route.ts
apps/web/app/api/v1/utils/types.ts
packages/open-api/karakeep-openapi-spec.json
packages/open-api/lib/bookmarks.ts
packages/open-api/lib/lists.ts
packages/open-api/lib/tags.ts
packages/open-api/package.json
packages/open-api/tsconfig.json
packages/sdk/src/karakeep-api.d.ts

* Addresses the comment by @thiswillbeyourgithub
* https://github.com/karakeep-app/karakeep/pull/1392#issuecomment-2870028422
* added/verified `sortOrder` functionality in the api for relevant resources
* update open-api docs
Technically this should be merged after #1392
Btw I'm not sure how much CI magic has been setup and if there are more docs or tasks that I also need to update for this PR, so please let me know if I missed anything.

feat(api): enable ?sortOrder= for relevant resources

---

docs/docs/13-community-projects.md

Just adding a link to my script that allows to send the RSS item I mark as *favourite* directly to karakeep as bookmarks.
Btw I don't know if you plan on doing this but on every new karakeep release I think it would be nice to shoutout new community projects made since the latest release in the release message, as I don't want to miss new contributions!

doc: new comunity project: freshrss to karakeep

---

apps/web/lib/i18n/locales/en_US/translation.json
packages/db/schema.ts
packages/shared/queues.ts
packages/shared/types/webhooks.ts
packages/trpc/routers/bookmarks.ts

Add support to a `deleted` webhook event, that is triggered when a user deletes a bookmark. Fixes #1463.

feat: handle "deleted" webhook events

---

apps/mobile/app/dashboard/bookmarks/[slug]/index.tsx
apps/mobile/components/bookmarks/BookmarkLinkPreview.tsx

Creates a new reader view as the default display for bookmarked articles (links) when list items are tapped, i.e. the bookmark detail view.
When a link bookmark was successfully scraped from a web page source (likely an article) HTML will be available on request as `bookmark.content.htmlContent`. This PR makes the change firstly to request this by setting request flag `includeContent`, and then if content is present, to display it in-line in the app. If no content is available, the link will fallback to the previous behaviour of using an embedded
Note:
- the usage of `bookmark.content.htmlContent` is assumed safe and depends on any previous efforts to clean this at the time the bookmark was added and processed
- users may still access the original link using the link/globe icon in the app …

feat(mobile): add reader view by default to bookmark detail view

---

start-dev.sh

* add simple script to start local dev environment
Actually, i would prefer doing `docker compose up -d`, but it's not working perfectly at the moment. Even when it's perfect, there might be people who prefer not to use docker for dev, so maybe we can keep this even after that.
But I'm not sure if we want this or not yet, but if this is welcomed, I'll update the docs as well to mention this.

chore: add start-dev.sh for laziness

---

apps/workers/workers/videoWorker.ts

In the event that yt-dlp errors out, the error details should be logged.
This can be helpful in deciding if and what extra arguments need to be passed via `CRAWLER_YTDLP_ARGS`.
yt-dlp prints out the error message to stderr.

fix(workers): video downloader should log yt-dlp errors

---

apps/web/components/admin/UserList.tsx
apps/web/lib/i18n/locales/en/translation.json

This PR enhances the user deletion UX in the Admin User List by adding a confirmation dialog to prevent accidental deletions
Closes #1648 
🧾 Changes Made:
💬Action confirmation dialog (ActionConfirmingDialog) wraps the delete button for each user.
🧠 State: Added local userToDelete state to manage dialog visibility and context.
🎨 Updated translation file:
Added: "delete_user_confirm_description": "Are you sure you want to delete user \"{{name}}\"?"

feat(admin): add confirmation dialog for user deletion (#1648)

---

apps/mobile/app/dashboard/bookmarks/[slug]/manage_tags.tsx

Having the search bar hidden in tags list makes no sense, this makes sure it's always visible.

UI Fix: Immediately visible search bar in tags list

---

apps/mobile/app/dashboard/bookmarks/[slug]/manage_tags.tsx

Added a "Clear All" button to the tag manager because AI often generates way too many tags and it's super annoying to remove them one by one. This makes it easier to clean everything up with a single tap.

feat: Clear all tags on mobile

---

apps/web/components/settings/ImportExport.tsx

In my opinion, the icons for import and export are reversed from what a user would expect them to be.
All this PR does is switch the "Download" and "Upload" symbols in the Import/Export settings menu!
| Current  | My Changes |
| ------------- | ------------- |
| ![image](https://github.com/user-attachments/assets/5e210244-4654-4044-b80d-636574e10367)  | ![image](https://github.com/user-attachments/assets/4359a155-04cf-4a24-af10-3fc25b2b387f)  |
(A world of difference, I know)

fix: switch import / export icons

---

apps/mcp/src/lists.ts

Linked to [issues 1696](https://github.com/karakeep-app/karakeep/issues/1696)

fix: add empty params object to lists function in mcp

---

apps/browser-extension/package.json
apps/browser-extension/vite.config.ts
pnpm-lock.yaml

Update @crxjs/vite-plugin to v2.0.1 and add server CORS configuration to allow requests from chrome-extension origins in the browser extension's vite.config.ts file. https://github.com/crxjs/chrome-extension-tools/blob/55912418204c6dbdbf7a4a59d1384a290208fb4d/playgrounds/react/vite.config.ts#L20
#670

feat: add CORS configuration for chrome-extension origin

---

apps/mobile/components/bookmarks/BookmarkLinkPreview.tsx

The mobile app uses a WebView to display the bookmark preview.
WebView on iOS has a `"fast"` deceleration rate by default, which doesn't match the rest of the app and makes scrolling through long articles tedious.
We should update it to `"normal"` to match the non-WebView screens in the app as well as Safari.
https://github.com/react-native-webview/react-native-webview/blob/master/docs/Reference.md#decelerationrate
Issue: #1834
<table>
<tr>
<td>fast (old behavior)</td>
<td>normal (new behavior)</td
</tr>
<tr>
<td>
<video src=https://github.com/user-attachments/assets/7f594d06-2543-40ab-8e98-3b7a8e168ac9>
</td>
<td>
<video src=https://github.com/user-attachments/assets/e63bf131-fda9-498e-bd2d-bd458c987628>
</td>
</tr>
</table>

ui(mobile): Fix WebView deceleration rate on iOS

---

packages/shared/assetdb.ts
packages/trpc/lib/attachments.ts

This commit allows the following mime types to be uploaded and attached as video assets on bookmarks.
- video/mp4
- video/webm
- video/x-matroska
This seems to be the minimal diff that adds the functionality in my dev environment. This change only adds the functionality to the API and makes no UI facing changes. Videos uploaded and attached using the API appear on the related bookmark similar to a video added using the native yt-dlp functionality.
I'm happy to make any changes needed to help land this.
Thanks for the amazing app!

feat: Support video uploads and attachments

---

apps/web/components/dashboard/bookmarks/SummarizeBookmarkArea.tsx
apps/web/components/ui/markdown/markdown-readonly.tsx

Wrap bookmark summary with MarkdownReadonly component to render Markdown properly.
Indeed, LLM answer are mostly in Markdown.
So now, line break, lists, bold and so on will make the summary far more readable.

Render AI summary in markdown

---

apps/browser-extension/src/components/ListsSelector.tsx
apps/browser-extension/src/components/TagsSelector.tsx
apps/browser-extension/src/components/ui/dynamic-popover.tsx
apps/browser-extension/src/components/ui/popover.tsx

**Related Issue**: 
#1580
#1840 
This PR addresses an issue with the expanded list picker placement in the Chrome extension, making it difficult or impossible to choose the first lists when there are many lists. The fix ensures the popover content adapts to the available viewport height, preventing overflow issues.
- **Problem**: The list selector popover was not properly handling viewport constraints, causing the first items to be hidden when opened near the bottom of the screen
- **Solution**: Added `h-[var(--radix-popover-content-available-height)]` class to the PopoverContent component to dynamically adjust height based on available space
- **Impact**: Users can now access all list items regardless of popover position
- Users with over 15 lists experienced difficulty accessing the …

fix(extension): constrain height to prevent viewport overflow (#1580)
